[versions]
jspecify = "1.0.0"
jetbrainsAnnotations = "26.1.0"
slf4j = "2.0.1"
junit = "6.1.1"
indra = "4.0.0"

[libraries]
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

[plugins]
indraLicenserSpotless = { id = "net.kyori.indra.licenser.spotless", version.ref = "indra" }